language: node_js
node_js:
  - 5.4.0
branches:
  only:
    - master
script: ./deploy.sh
env:
  global:
    - GH_REF: github.com/scott113341/post.git
    - secure: X4NizTwKu0eH1fy9s8ZwB3RFoiCIyFncKRB3W8VquqBBQKWNgunIurOB7r3U/RN8Zk59HK/1CWv5la03Q7xBLbBl+nimgclsENICvwKa+KDrKtIQKRrTJYu2JDLeZCs3J8yhS5ReAR/MSf/0iE8AcW2ypq9CY9qnmw5LYFg5WGWIemQe9A3+CvRzu1MU5/YpuuKPKtUjCQJBhbgYAcybRfOdMwIk893LAbD4iLfWjYRIZyd7WhUjqkFGvqCgW0SN5NZPEnFoesRZdIhRQyvWCmVI4+QngCdWE+I+9/NRX5w83L7DVPTFBOuKxMkCIJp6Ch3bydrlp4RK9b7F5L4FL0wI9QZ4zh+hDt8kABdNQWTVogjc1mJyjxZAJ2VRJxcgHRBEpos+T01rVIjtq3feCNDu8GtPO+Lj0tHO1+6o2ABBjYoKLjIucl3NvIhoinCPa0r9EufcX4yqT5UBEyie35lHFlvm54ZNq4xy5uKyQx4JKFkSUV6/mCzkmJ2C2zP8TpzXpGu8rsPwh7qs/R8ZHm8+4G+iHi41VAdPAPd8pkAc04huzrp+3U+Ej5CRAse/VuXoGRLeFIt86z5zzRj48pRpNkf5iYRpeye+D6Jar6TgCnG2W6rFGoY0zYu5YXDz4PlZwmFw+zYlhGDI8r4p4wdkNddPumfzyQ7bbK1h04E=
