language: node_js
node_js:
  - 5.4.0
branches:
  only:
    - master
script: ./deploy.sh
env:
  global:
    - GH_REF: github.com/scott113341/post.git
    - secure: s3edT25c0HPbrNV1zR9x9mAPDkdceyBAXaCmWcfSWe3t+PE0CuNvJ33DsOdh0pt0+qzuvRmPjUniX9bvKSD3RBB2+qOuCGBfya1QBahm94XMYVyinqDcTZ65cz9bgSdhSuwLgVTA6H8oA1DgiB5WLFdf25LaZlxgmvP4wpD21BgFKy09hDYmtF1H662s7x6DUPa8PL2wPIqn0jbay7yvRMfn0hqbB9Yp4FPUqmKsrKodRtfDD4cTmNNdPFJivOE8fvbJtLKDyAxSiQlqVwZ7WU/05yegJDcGDyt94R8E193sgMSrOn4NFJJIIzlyxA4E4RlNRhT2Kn+9MXsTBjWLrLTuCfIhe6HKVHfKHoWEtTGSI6JwwrIDuqMrmhCPC2umjj/bviYdrmTcmLyBgNx+XDo1KsB3LUetuVJ/bNCz8dEXgRWTvismN8bJ8sWvMPu7BVQdeBebvQdLwS8EdrT5f+QePaCoLzCIWf7Oh95YL0iqsaFCL/g4ynf6MM/vpXnxMXqxX8q3k9AAUYN1I5soY1OnG5LKIN8vGczwMXS4LmIWIMojDVzqN8JOmqTlQqwj1QE9/ZyXgoY4zfL6bLqjFXbOhG+7gIJ9RolgbLoHjdizve5HSVuwVmiXhV4dSuwTrmn57AN+0/oKuD0ltxEAySrLOsocuwYDl4WcG4YLkiA=
