language: node_js
node_js:
  - '5.4.0'
branches:
  only:
    - master
script: ./deploy.sh
env:
  global:
    - GH_REF: github.com/scott113341/post.git
    - secure: NjxfptOuncgyIi4KvJqcLxpWHllSjm4txiTIBMhpaEqbL1MuIZscqfGtuy/Ctc29EYxF+Xr+FbpTAXSTpSiWpGAKeKfm+b6ZprOkyUihh36FBcA5L3JMC6COxIOeOVXAl/Dqd9VvM4p0nL1UqxBp10RuZkuN5W6Df9CNCbdmbl3N65UYEcc4tIiTmksBgdjAMeB9Z7XgZRdWyRDTOApPt84QJnS5RnoFULGyLBaOJAEVnMOJgQlaP3LxS25B25F3o1BiwlGZbDEGlMYf56Pe9EdMfgBPcmex7a/khZ9Vd2yMP61UmqMTPpE5RNi/8kGFs71Zw9cXEHhQhxdpQ7DKW8UhdHW4YOVf/atRNCgWWgNUwPJxKsRXZtHBC3iG/taeCCYlk+5RWlZc6PJKFqCJZgl48rkI0CwynrmF+1kdN2z6YYqcCvur9UOZTVA0sZQCMHCktT6PwUZ7RbJTfwrGcSCCbCiyqIbY1pjP4kYYlue31tsZemL92cYWxjjiCgV/WOs5Sol6idOBVKLce1dYcxfLeQIBPKCjIyk2wEcU5MbB6TscO7XfzMJOzUrCUSHAEncmh9WH9rddeJDMNUp4R0XkWEyFczY2G/TuPkySViEYOSNZX6MNyDN3R6685yydxeYdHwwJ6tL0c4fMSb1L3TQD13VDoJc6+5/mVLgUC2k=
